# Generated by Django 3.2.5 on 2021-07-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('lyrics', models.CharField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
