# Generated by Django 3.2.5 on 2021-07-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_rename_songs_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='lyrics',
            new_name='verses',
        ),
    ]
