# Generated by Django 3.2.5 on 2021-07-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_rename_lyrics_song_verses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='verses',
            new_name='lyrics',
        ),
    ]
