# Generated by Django 3.2.5 on 2021-07-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_rename_verses_song_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='verses',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
