# Generated by Django 3.2.5 on 2021-08-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_alter_song_verses'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
