# Generated by Django 3.2.5 on 2021-12-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_song_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
