# Generated by Django 3.2.5 on 2021-12-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_song_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='color',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
